DROP TABLE IF EXISTS Empregado;
DROP TABLE IF EXISTS Departamento;
DROP TABLE IF EXISTS Equipe;
DROP TABLE IF EXISTS Projeto;
DROP TABLE IF EXISTS Tarefa;
DROP TABLE IF EXISTS Etapa;
DROP TABLE IF EXISTS Tarefa_Empregado;
DROP TABLE IF EXISTS Telefone;